{
 "title": "MLOps Loop",
 "tags": [ "mlops-lab" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[1m])"
    }
   ]
  },
  {
   "title": "p95 latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(prediction_latency_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Median predicted value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(prediction_value_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Prediction distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(prediction_value_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}